import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const TRIGGER_KEY=Deno.env.get("SCHEDULER_TRIGGER_KEY")||"4u5QmV1g8H9sP2kR7xN3zL6cT0wY5bA1";const SEND_URL=`${SUPABASE_URL}/functions/v1/send-fcm-notification`;
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type, x-scheduler-key","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:cors})}
async function db(path:string,init:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,"Content-Type":"application/json",...(init.headers||{})}})}
async function send(title:string,message:string){const r=await fetch(SEND_URL,{method:"POST",headers:{"x-scheduler-key":TRIGGER_KEY,"Content-Type":"application/json"},body:JSON.stringify({title,message})});const t=await r.text();let d:any={};try{d=JSON.parse(t)}catch{d={raw:t}}if(!r.ok||d.success===false)throw new Error(d.error||`FCM failed (${r.status})`);return d}
function parts(now=new Date()){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).formatToParts(now);const g=(t:string)=>p.find(x=>x.type===t)?.value||"00";return {today:`${g("year")}-${g("month")}-${g("day")}`,hhmm:`${g("hour")}:${g("minute")}`,year:Number(g("year")),month:g("month"),day:g("day")}}
function displayName(name:string){const n=name.trim();return /નળીયાપરા\s*$/u.test(n)?n:`${n} નળીયાપરા`}
function birthdayMessage(name:string,village:string){return `${displayName(name)} (${village.trim()}) ને જન્મદિવસની ખૂબ ખૂબ શુભેચ્છાઓ! 🎉🎂\nનળીયાપરા પરિવાર તરફથી હાર્દિક શુભકામનાઓ. ❤️`}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.headers.get("x-scheduler-key")!==TRIGGER_KEY)return json({ok:false,error:"Scheduler access denied"},403);try{
 const now=parts();const results:any[]=[];
 const sr=await db(`notification_schedules?enabled=eq.true&send_time=lte.${now.hhmm}:59&or=(last_sent_date.is.null,last_sent_date.neq.${now.today})&select=*`);const schedules=await sr.json();if(!sr.ok)throw new Error(JSON.stringify(schedules));
 for(const s of(Array.isArray(schedules)?schedules:[])){try{const f=await send(String(s.title),String(s.message));await db(`notification_schedules?id=eq.${encodeURIComponent(s.id)}`,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({last_sent_date:now.today})});await db("notification_logs",{method:"POST",body:JSON.stringify({kind:"scheduled",schedule_id:s.id,title:s.title,message:s.message,success:true})});results.push({type:"schedule",id:s.id,success:true,fcm:f})}catch(e){const m=e instanceof Error?e.message:String(e);await db("notification_logs",{method:"POST",body:JSON.stringify({kind:"scheduled",schedule_id:s.id,title:s.title,message:s.message,success:false,error:m})});results.push({type:"schedule",id:s.id,success:false,error:m})}}
 const br=await db(`birthday_contacts?active=eq.true&birth_date=gte.2000-${now.month}-${now.day}&birth_date=lt.2100-${now.month}-${now.day}&select=*`);let birthdays=await br.json();if(!br.ok)throw new Error(JSON.stringify(birthdays));
 // The date filter above is month/day based by construction: we still verify month/day in JS to avoid DB date edge cases.
 birthdays=Array.isArray(birthdays)?birthdays.filter((b:any)=>{const s=String(b.birth_date||"");return s.slice(5)===`${now.month}-${now.day}`}):[];
 for(const b of birthdays){const title="🎂 જન્મદિવસની હાર્દિક શુભેચ્છાઓ";const message=birthdayMessage(String(b.name),String(b.village));try{
   const existing=await db(`birthday_notification_logs?birthday_contact_id=eq.${encodeURIComponent(b.id)}&birthday_year=eq.${now.year}&select=id&limit=1`);const ex=await existing.json();if(!existing.ok)throw new Error(JSON.stringify(ex));if(Array.isArray(ex)&&ex.length){results.push({type:"birthday",id:b.id,success:true,skipped:true,reason:"already_sent"});continue}
   const f=await send(title,message);const lr=await db("birthday_notification_logs",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates"},body:JSON.stringify({birthday_contact_id:b.id,birthday_year:now.year,title,message,success:true})});if(!lr.ok)throw new Error(await lr.text());results.push({type:"birthday",id:b.id,success:true,fcm:f})
 }catch(e){const m=e instanceof Error?e.message:String(e);await db("birthday_notification_logs",{method:"POST",headers:{Prefer:"resolution=ignore-duplicates"},body:JSON.stringify({birthday_contact_id:b.id,birthday_year:now.year,title,message,success:false,error:m})});results.push({type:"birthday",id:b.id,success:false,error:m})}}
 return json({ok:true,date:now.today,time:now.hhmm,processed:results.length,results})
}catch(e){return json({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
